# Generated by Django 3.2.4 on 2021-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='First Name')),
                ('email', models.EmailField(max_length=30, verbose_name='Email Address')),
            ],
        ),
    ]
